name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Please double check the [Common Issues](https://github.com/samemory/homebridge-eufy-security/wiki/Common-Issues) before submitting a request.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: dropdown
    id: device_type
    attributes:
      label: Device Type
      description: On which device your facing issue?
      options:
        - Doorbell (Supported)
        - Floodlight (Supported)
        - Indoor Camera (Supported)
        - Motion Detector (Supported)
        - Contact Sensor (Supported)
        - Station (Supported)
        - other (UnSupported)
    validations:
      required: true

  - type: dropdown
    id: plugin_version
    attributes:
      label: Plugin Version
      description: What version of the plugin are you running?
      options:
        - v2.0.x (Supported)
        - beta (Best Effort)
        - other (UnSupported)
    validations:
      required: true

  - type: dropdown
    id: hb_version
    attributes:
      label: HomeBridge Version
      description: What version of homebridge are you running?
      options:
        - v1.6.x (Supported)
        - v1.4.x (UnSupported)
        - v1.3.x (UnSupported)
        - other (UnSupported)
    validations:
      required: true

  - type: dropdown
    id: node_version
    attributes:
      label: NodeJS Version
      description: What NodeJS version used to run homebridge?
      options:
        - v18 (Supported)
        - v16 (UnSupported)
        - other (UnSupported)
    validations:
      required: true

  - type: dropdown
    id: os_type
    attributes:
      label: Operating System
      description: What OS used to run homebridge?
      options:
        - Raspbian 10+ (Supported)
        - Ubuntu 18.04+ (Supported)
        - Debian 10+ (Supported)
        - Windows 10+ (UnSupported)
        - Mac OS X 11+ (UnSupported)
        - Docker (UnSupported)
        - Other (UnSupported)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: config
      description: Please copy and paste your config json. Please make sure to remove any private information.
      render: shell
    validations:
      required: true
